version: '3'

services:
  core-api:
    image: 'node:14.9.0'
    working_dir: '/home/app-name'
    volumes:
      - ./:/home/app-name
    command: "sh -c 'npm install && npm run start:dev ' "
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
#  postgres:
#      container_name: postgres
#      image: postgres:latest
#      env_file:
#        - database.env # configure postgres
#      volumes:
#        - ./data/postgres/pgdata:/var/lib/postgresql/data
#      ports:
#        - 5432:5432



