version: '3.3'

services:
#  server:
#    container_name: main
#    build:
#      context: .
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3000:3000
#    command: npm run start:dev
#    env_file:
#      - .env
#    depends_on:
#      - postgres
  postgres:
      container_name: postgres
      image: postgres:latest
      env_file:
        - .env
      volumes:
        - ./data/postgres/pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432



